"""Initial Schema

Revision ID: 8a959a847997
Revises: None
Create Date: 2026-08-22 12:07:35.096140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a959a847997'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.create_table('forecasts',
    sa.Column('forecast_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('predicted_demand', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=False),
    sa.Column('upper_bound', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('forecast_id')
    )
    op.create_index(op.f('ix_forecasts_forecast_date'), 'forecasts', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_forecasts_forecast_id'), 'forecasts', ['forecast_id'], unique=False)
    op.create_index(op.f('ix_forecasts_product_id'), 'forecasts', ['product_id'], unique=False)
    op.create_index(op.f('ix_forecasts_target_date'), 'forecasts', ['target_date'], unique=False)
    op.create_table('inventory',
    sa.Column('inventory_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('opening_stock', sa.Integer(), nullable=False),
    sa.Column('units_received', sa.Integer(), nullable=False),
    sa.Column('units_sold', sa.Integer(), nullable=False),
    sa.Column('closing_stock', sa.Integer(), nullable=False),
    sa.Column('reserved_stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    op.create_index(op.f('ix_inventory_inventory_id'), 'inventory', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_snapshot_date'), 'inventory', ['snapshot_date'], unique=False)
    op.create_table('risk_events',
    sa.Column('risk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('evaluation_date', sa.Date(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('forecast_demand_7d', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('days_to_stockout', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('risk_id')
    )
    op.create_index(op.f('ix_risk_events_evaluation_date'), 'risk_events', ['evaluation_date'], unique=False)
    op.create_index(op.f('ix_risk_events_product_id'), 'risk_events', ['product_id'], unique=False)
    op.create_index(op.f('ix_risk_events_risk_id'), 'risk_events', ['risk_id'], unique=False)
    op.create_index(op.f('ix_risk_events_risk_level'), 'risk_events', ['risk_level'], unique=False)
    op.create_table('sales',
    sa.Column('sale_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('units_sold', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('promotion', sa.Boolean(), nullable=False),
    sa.Column('discount_pct', sa.Float(), nullable=False),
    sa.Column('sales_channel', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('sale_id')
    )
    op.create_index(op.f('ix_sales_product_id'), 'sales', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_sale_date'), 'sales', ['sale_date'], unique=False)
    op.create_index(op.f('ix_sales_sale_id'), 'sales', ['sale_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('order_accuracy', sa.Float(), nullable=False),
    sa.Column('minimum_order_qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_index(op.f('ix_suppliers_product_id'), 'suppliers', ['product_id'], unique=False)
    op.create_index(op.f('ix_suppliers_supplier_id'), 'suppliers', ['supplier_id'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('expected_delivery', sa.Date(), nullable=False),
    sa.Column('actual_delivery', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_order_date'), 'orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_orders_product_id'), 'orders', ['product_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_supplier_id'), 'orders', ['supplier_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('recommendation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('recommendation_date', sa.Date(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('recommended_action', sa.String(length=100), nullable=False),
    sa.Column('recommended_quantity', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.String(length=50), nullable=False),
    sa.Column('supplier_score', sa.Float(), nullable=False),
    sa.Column('estimated_unit_cost', sa.Float(), nullable=False),
    sa.Column('estimated_purchase_value', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_index(op.f('ix_recommendations_product_id'), 'recommendations', ['product_id'], unique=False)
    op.create_index(op.f('ix_recommendations_recommendation_date'), 'recommendations', ['recommendation_date'], unique=False)
    op.create_index(op.f('ix_recommendations_recommendation_id'), 'recommendations', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendations_supplier_id'), 'recommendations', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_supplier_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_recommendation_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_recommendation_date'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_product_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_orders_supplier_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_product_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_date'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_suppliers_supplier_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_product_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_sales_sale_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_sale_date'), table_name='sales')
    op.drop_index(op.f('ix_sales_product_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_risk_events_risk_level'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_risk_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_product_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_evaluation_date'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_inventory_snapshot_date'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_inventory_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_forecasts_target_date'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_product_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_forecast_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_forecast_date'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
